name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update deps
      run: sudo apt-get -y update
    - name: install deps
      run: sudo apt install pkgconf libsdl1.2-compat-dev libsdl-gfx1.2-dev
    - name: make sdl1
      run: make clean && make
